### PR TITLE
Entire site

### PR DESCRIPTION
**Pull request by yghoor**
## Build event site according to spec from curriculum-html-css/capstone/html_capstone.md

Built following the design by [Cindy Shin](https://www.behance.net/adagio07) in [Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) as per the spec

### CODE REVIEW

**Comment by Cerdtruir** [comment]
The footer is supposed to be white on mobile

**Comment by Cerdtruir** [comment]
The home page needs a small heading on top of the main one.
Please read the review guidelines before requesting a review. You can let me know when this is ready for a review.

**Comment by yghoor** [comment]
Made requested changes

**Review by ikraamg — APPROVED** [review]
Looks great! 🚀

**Comment by ikraamg** [comment]
@yghoor I notice that there is something affecting the mobile view on the right. See if you can fix it and then merge 👍 

image

**Pull request merged**
